In [1]:
import pandas as pd 
import numpy as np

In [2]:
# import csv file in python labraries
df=pd.read_csv("phone pay data.csv")

In [3]:
# Display first 5 rows
df.head()

,Transaction_ID,Transaction_Date,Transaction_Time,UPI_App,Customer_ID,Age_Group,Gender,State,City,Merchant_Name,...,Payment_Mode,Bank_Name,Amount_INR,Cashback_INR,Transaction_Fee_INR,Status,Failure_Reason,Device_OS,Risk_Score,Is_Suspected_Fraud
0,UPI202605P2_0000001,5/28/2026,17:01:47,PhonePe,CUST882856,25-34,Male,Telangana,Warangal,Topmate,...,Bank Account,Bank of Baroda,572.53,51.80,0.0,Success,NaN,iOS,7,No
1,UPI202605P2_0000002,5/10/2026,12:14:08,Google Pay,CUST170502,25-34,Female,Tamil Nadu,Chennai,Udemy,...,UPI ID,Axis Bank,415.75,0.00,0.0,Success,NaN,Android,72,No
2,UPI202605P2_0000003,5/4/2026,19:43:47,Paytm,CUST107673,35-44,Male,Delhi,New Delhi,Local Clinic,...,QR Scan,Punjab National Bank,1007.05,22.81,0.0,Success,NaN,Android,29,No
3,UPI202605P2_0000004,5/14/2026,20:05:37,PhonePe,CUST817281,35-44,Female,Telangana,Nizamabad,Indian Oil,...,QR Scan,HDFC Bank,390.86,0.00,0.0,Success,NaN,Android,93,Yes
4,UPI202605P2_0000005,5/11/2026,14:01:05,Amazon Pay,CUST513285,45-54,Female,Gujarat,Surat,Data Tutorials,...,UPI ID,Punjab National Bank,165.15,15.37,0.0,Success,NaN,iOS,25,No

In [4]:
# Display row and column
df.shape

(50000, 22)

In [5]:
# Display all column name 
df.columns

Index(['Transaction_ID', 'Transaction_Date', 'Transaction_Time', 'UPI_App',
       'Customer_ID', 'Age_Group', 'Gender', 'State', 'City', 'Merchant_Name',
       'Merchant_Category', 'Transaction_Type', 'Payment_Mode', 'Bank_Name',
       'Amount_INR', 'Cashback_INR', 'Transaction_Fee_INR', 'Status',
       'Failure_Reason', 'Device_OS', 'Risk_Score', 'Is_Suspected_Fraud'],
      dtype='object')

In [6]:
# Check Data types
df.dtypes

Transaction_ID          object
Transaction_Date        object
Transaction_Time        object
UPI_App                 object
Customer_ID             object
Age_Group               object
Gender                  object
State                   object
City                    object
Merchant_Name           object
Merchant_Category       object
Transaction_Type        object
Payment_Mode            object
Bank_Name               object
Amount_INR             float64
Cashback_INR           float64
Transaction_Fee_INR    float64
Status                  object
Failure_Reason          object
Device_OS               object
Risk_Score               int64
Is_Suspected_Fraud      object
dtype: object

In [7]:
# Check the data information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction_ID       50000 non-null  object
 1   Transaction_Date     50000 non-null  object
 2   Transaction_Time     50000 non-null  object
 3   UPI_App              50000 non-null  object
 4   Customer_ID          50000 non-null  object
 5   Age_Group            50000 non-null  object
 6   Gender               50000 non-null  object
 7   State                50000 non-null  object
 8   City                 50000 non-null  object
 9   Merchant_Name        50000 non-null  object
 10  Merchant_Category    50000 non-null  object
 11  Transaction_Type     50000 non-null  object
 12  Payment_Mode         50000 non-null  object
 13  Bank_Name            50000 non-null  object
 14  Amount_INR           50000 non-null  float64
 15  Cashback_INR         50000 non-null  float64
 16  Transaction_Fee_INR  50000 non-null  float64
 17  Status               50000 non-null  object
 18  Failure_Reason       4575 non-null   object
 19  Device_OS            50000 non-null  object
 20  Risk_Score           50000 non-null  int64
 21  Is_Suspected_Fraud   50000 non-null  object
dtypes: float64(3), int64(1), object(18)
memory usage: 8.4+ MB

In [8]:
# Convert the transaction date into currect date format
df["Transaction_Date"]=pd.to_datetime(df["Transaction_Date"])
df["Transaction_Date"]

0       2026-05-28
1       2026-05-10
2       2026-05-04
3       2026-05-14
4       2026-05-11
           ...
49995   2026-05-28
49996   2026-05-11
49997   2026-05-01
49998   2026-05-19
49999   2026-05-28
Name: Transaction_Date, Length: 50000, dtype: datetime64[ns]

In [9]:
# Convert the transaction time into currect time format
df["Transaction_Time"] =pd.to_datetime(df["Transaction_Time"],format="%H:%M:%S").dt.time
df["Transaction_Time"]

0        17:01:47
1        12:14:08
2        19:43:47
3        20:05:37
4        14:01:05
           ...
49995    16:34:55
49996    20:38:38
49997    14:22:38
49998    17:26:48
49999    15:56:38
Name: Transaction_Time, Length: 50000, dtype: object

In [10]:
# Data Cleaning

# Check Missing Value
df.isnull().sum()

Transaction_ID             0
Transaction_Date           0
Transaction_Time           0
UPI_App                    0
Customer_ID                0
Age_Group                  0
Gender                     0
State                      0
City                       0
Merchant_Name              0
Merchant_Category          0
Transaction_Type           0
Payment_Mode               0
Bank_Name                  0
Amount_INR                 0
Cashback_INR               0
Transaction_Fee_INR        0
Status                     0
Failure_Reason         45425
Device_OS                  0
Risk_Score                 0
Is_Suspected_Fraud         0
dtype: int64

In [11]:
# Check Duplicate Transactions
df["Transaction_ID"].duplicated().sum()

np.int64(0)

In [12]:
# check status frequently count
df["Status"].value_counts()

Status
Success    45425
Failed      3568
Pending     1007
Name: count, dtype: int64

In [13]:
# Risk Score Range min to max
df["Risk_Score"].min(),df["Risk_Score"].max()

(1, 100)

In [14]:
# Extracted hour from transaction time 
df["Hour"]=pd.to_datetime(df["Transaction_Time"],format="%H:%M:%S").dt.hour
df[["Transaction_Time","Hour"]]

      Transaction_Time  Hour
0             17:01:47    17
1             12:14:08    12
2             19:43:47    19
3             20:05:37    20
4             14:01:05    14
...                ...   ...
49995         16:34:55    16
49996         20:38:38    20
49997         14:22:38    14
49998         17:26:48    17
49999         15:56:38    15

[50000 rows x 2 columns]

In [15]:
# Extracted day name from the date
df["Day"]=df["Transaction_Date"].dt.day_name()
df[["Transaction_Date","Day"]]

      Transaction_Date       Day
0           2026-05-28  Thursday
1           2026-05-10    Sunday
2           2026-05-04    Monday
3           2026-05-14  Thursday
4           2026-05-11    Monday
...                ...       ...
49995       2026-05-28  Thursday
49996       2026-05-11    Monday
49997       2026-05-01    Friday
49998       2026-05-19   Tuesday
49999       2026-05-28  Thursday

[50000 rows x 2 columns]

In [16]:
# Extracted the month name from the date
df["month"]=df["Transaction_Date"].dt.month_name()
df[["Transaction_Date","month"]]

      Transaction_Date month
0           2026-05-28   May
1           2026-05-10   May
2           2026-05-04   May
3           2026-05-14   May
4           2026-05-11   May
...                ...   ...
49995       2026-05-28   May
49996       2026-05-11   May
49997       2026-05-01   May
49998       2026-05-19   May
49999       2026-05-28   May

[50000 rows x 2 columns]

In [17]:
# classified transaction amount into low,medium,and high using numpy
df["Amount_Category"] = np.select(
    [df["Amount_INR"] < 500, df["Amount_INR"] < 2000],
    ["Low", "Medium"],
    default="High"
)

df[["Amount_INR","Amount_Category"]]

       Amount_INR Amount_Category
0          572.53          Medium
1          415.75             Low
2         1007.05          Medium
3          390.86             Low
4          165.15             Low
...           ...             ...
49995      470.10             Low
49996      135.65             Low
49997      302.27             Low
49998      353.89             Low
49999     1144.68          Medium

[50000 rows x 2 columns]

In [18]:
# Descriptive Statistical analysis of Amount_INR
print("Mean:", np.mean(df["Amount_INR"]))
print("Median:", np.median(df["Amount_INR"]))
print("Std:", np.std(df["Amount_INR"]))
print("Min:", np.min(df["Amount_INR"]))
print("Max:", np.max(df["Amount_INR"]))

Mean: 856.7767634
Median: 494.17
Std: 1267.998663535131
Min: 8.44
Max: 55315.85

In [19]:
# check total transaction 
total_transactions = df["Transaction_ID"].nunique()
print("Total_transactions:",total_transactions)

Total_transactions: 50000

In [20]:
# check total amount 
total_amount=df["Amount_INR"].sum()
print("Total_amount:",total_amount)

Total_amount: 42838838.17

In [21]:
# check total Cashback
total_cashback = df["Cashback_INR"].sum() 
print("Total_cashback:",total_cashback)

Total_cashback: 344665.67

In [22]:
# Calculate the success of transaction 
success_rate = (df["Status"].eq("Success").mean()*100)
print("success_rate:",success_rate)

success_rate: 90.85

In [23]:
# Check the fraud transaction count
df["Is_Suspected_Fraud"].value_counts()

Is_Suspected_Fraud
No     48292
Yes     1708
Name: count, dtype: int64

In [24]:
# Calculate states-wise transaction amount
state_analysis = df.groupby("State") ["Amount_INR"].sum().sort_values(ascending=False) 
print("state_analysis:",state_analysis)

state_analysis: State
Gujarat           4541033.09
Tamil Nadu        4399877.50
Telangana         4357414.47
Uttar Pradesh     4327060.39
Delhi             4270726.72
Karnataka         4245821.46
Madhya Pradesh    4239809.02
Rajasthan         4225874.92
West Bengal       4180416.54
Maharashtra       4050804.06
Name: Amount_INR, dtype: float64

In [25]:
# Calculate UPI app-wise transaction amount
upi_analysis = df.groupby("UPI_App")["Amount_INR"].sum().sort_values(ascending=False)
print("upi_analysis:",upi_analysis)

upi_analysis: UPI_App
PhonePe         20661531.92
Google Pay       9390505.36
Paytm            6268384.46
Amazon Pay       2240350.55
BHIM             1710650.66
Cred Pay         1314167.32
WhatsApp Pay     1253247.90
Name: Amount_INR, dtype: float64

In [26]:
# Calculate transaction type-wise amount
transaction_type_analysis = df.groupby("Transaction_Type")["Amount_INR"].sum().sort_values(ascending=False)
print("transaction_type_analysis:",transaction_type_analysis)

transaction_type_analysis: Transaction_Type
P2M                17894871.58
P2P                 8722445.47
Bill Payment        5965021.89
Online Shopping     3882703.16
Recharge            3292983.54
Subscription        1804655.46
Wallet Transfer     1276157.07
Name: Amount_INR, dtype: float64

In [27]:
# Cheak the no.of rows and columns
df.shape

(50000, 26)

In [28]:
# check missing values in each column 
df.isnull().sum()

Transaction_ID             0
Transaction_Date           0
Transaction_Time           0
UPI_App                    0
Customer_ID                0
Age_Group                  0
Gender                     0
State                      0
City                       0
Merchant_Name              0
Merchant_Category          0
Transaction_Type           0
Payment_Mode               0
Bank_Name                  0
Amount_INR                 0
Cashback_INR               0
Transaction_Fee_INR        0
Status                     0
Failure_Reason         45425
Device_OS                  0
Risk_Score                 0
Is_Suspected_Fraud         0
Hour                       0
Day                        0
month                      0
Amount_Category            0
dtype: int64

In [29]:
# check duplicate rows
df.duplicated().sum()

np.int64(0)

In [30]:
# Exported the cleaned data to a CSV file 
df.to_csv("phone_pay_data.csv",index =False)